[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
fs = "0.0.5"
lazy_static = "1.5.0"
regex = "1.11.1"
chrono = "0.4"
users = "0.11"
termion = "4.0.5"
whoami = "1.6.0"
